services:
  app:
    build: .
    ports:
      - "9876:9876"
    volumes:
      - ./data:/app/data
      - ./pages:/app/pages
      - ./uploads:/app/uploads
    env_file:
      - path: .env
        required: false
    environment:
      - DOCKER=true
      - CHECKOUT_DRIVER=pix
    container_name: afiliafacil
